# YouTube client types
CLIENT_WEB = "WEB"
CLIENT_WEB_REMIX = "WEB_REMIX"
CLIENT_ANDROID = "ANDROID"
CLIENT_IOS = "IOS"

# Browse IDs
BROWSE_TRENDING = "FEtrending"
BROWSE_MUSIC_HOME = "FEmusic_home"
BROWSE_MUSIC_CHARTS = "FEmusic_charts"
BROWSE_MUSIC_MOODS = "FEmusic_moods_and_genres"
BROWSE_MUSIC_NEW_RELEASES = "FEmusic_new_releases"

# Search filter params
SEARCH_FILTER_VIDEO = "EgIQAQ%3D%3D"
SEARCH_FILTER_CHANNEL = "EgIQAg%3D%3D"
SEARCH_FILTER_PLAYLIST = "EgIQAw%3D%3D"

MUSIC_FILTER_SONGS = "EgWKAQIIAWoKEAoQAxAEEAkQBQ%3D%3D"
MUSIC_FILTER_VIDEOS = "EgWKAQIQAWoKEAoQAxAEEAkQBQ%3D%3D"
MUSIC_FILTER_ALBUMS = "EgWKAQIYAWoKEAoQAxAEEAkQBQ%3D%3D"
MUSIC_FILTER_ARTISTS = "EgWKAQIgAWoKEAoQAxAEEAkQBQ%3D%3D"
MUSIC_FILTER_PLAYLISTS = "EgWKAQIoAWoKEAoQAxAEEAkQBQ%3D%3D"
